//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWebStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Products
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Add product name!")]
        [StringLength(100, ErrorMessage = "Name can be max 100 characters in length!")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Add product price!")]
        public decimal Price { get; set; }

        [StringLength(1000, ErrorMessage = "Description can be max 1000 characters in length!")]
        public string Description { get; set; }
        public string Image { get; set; }
        public int CategoriesId { get; set; }

        public virtual Categories Categories { get; set; }
    }
}
